---
title: "ForestPlotCourseHonePage"
author: "Niclas Jonsson"
date: "5/23/2022"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Forest plots in practical use: Implementation and interpretation

## Welcome!

Welcome to the pre-PAGE 2022 workshop on *Forest plots in practical use*, given by Pharmetheus and tutored by Niclas Jonsson and Joakim Nyberg.

The workshop will take place on Tuesday 28th of June, 2022 (09:00-17:00 CEST/GMT+2), in connection to PAGE, in Ljubljana, Slovenia. The registration page and workshop description can be found at the [PAGE website](https://www.page-meeting.org/default.asp?id=47&keuze=meeting&mid=23).

The intention with this page is to give practical information regarding system requirements for the hands-on sessions and installation instructions for R-packages, as well as links to the course material.

## Workshop overview

The workshop aims at mixing lectures and hands-on sessions to provide an in-depth understanding of Forest plots, both from a theoretical as well as practical perspective.

The workshop runs between 09:00 and 17:00, with breaks for lunch and coffee. 

A detailed course schedule can be found **here**.


## Requirements

The participants are expected to bring their own laptops with R and Rstudio installed. It is also preferable if the R-packages necessary for the hands-on exercises are installed before the workshop starts. There will be Pharmetheus representatives available between 08:00 and 09:00 on the day of the workshop day to assist in the installation of the packages in case help is needed. However, the installation instructions are intended to be self-explanatory and easy to follow so hopefully no help will be needed. 

### R-version

R version 3.5.3 and 4.2...

### Installation of R-packages

To minimize the risk of R-package conflicts you will be able to download an installation package that contains all packages needed. With the help of the accompanying installation scipt you can install them in a way that should not create conflict with any existing R-package installations. Follow this link for further instructions and download links.


## Course material

### Handouts


You can find the lecture handouts **here**.

## Hands-on material

The hands-on instructions are availadbe **here** and the answers **here** (available after the hands-on session).



