---
NONMEM_directory: /usr/local/arch/nonmem/nonmem-7.3g53om20
NONMEM_version: '7.3'
PsN_version: 4.8.1
command_line: /opt/psn/psn-4.8.1/bin/sir -samples=1000,1000,2000 -resamples=200,500,1000
  run1.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: '2'
  compress: 0
  condition_number_limit: 1000
  correlation_limit: 0.85
  crash_restarts: 4
  degree: 0.1
  directory: /home/shared/Projects/Pharmetheus/PMX-MI-PMX-1/Analysis/Model/FRX/sir_dir1/
  display_iterations: 0
  handle_crashes: 1
  handle_msfo: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: '-99'
  model_subdir: 0
  near_bound_sign_digits: 2
  near_zero_boundary_limit: 0.01
  nice: 19
  nm_output: ext,cov,coi,cor,phi,shk
  nm_version: default
  nmfe: '1'
  nmfe_options: -tprdefault
  nmqual: 0
  nodes: 0
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: '1'
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 135678
  send_email: 0
  shrinkage: 0
  sign_digits_off_diagonals: 2
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /opt/psn/psn-4.8.1/PsN_4_8_1/R-scripts
  template_file_rplots: sir_default.R
  threads: '8'
  tweak_inits: 1
  verbose: 0
  zip: 0
finish_time: 2020-04-29 17:07:17
model_files:
- /home/shared/Projects/Pharmetheus/PMX-MI-PMX-1/Analysis/Model/FRX/run1.mod
start_time: 2020-04-29 16:02:24
tool_name: sir
tool_options:
  add_iterations: 0
  boxcox: 1
  cap_correlation: 0.8
  cap_resampling: 1
  copy_data: 1
  fast_posdef_checks: 0
  in_filter: ''
  mceta: 0
  offset_rawres: 1
  omega_inflation: '1'
  problems_per_file: 100
  recenter: 1
  resamples: 200,500,1000
  samples: 1000,1000,2000
  sigma_inflation: '1'
  theta_inflation: '1'
