#' Setup Reference Row(s) for Forest Plots
#'
#' @description Generates the reference data frame (`dfRefRow`) required by
#'   `getForestDF` functions. It computes the baseline reference values from the
#'   raw data and maps them to the structure of the provided `dfCovs`.
#'
#' @details
#'   The function computes the reference state (mode for categorical, mean/median
#'   for continuous) based on the deduplicated baseline data, ensuring mathematical
#'   consistency with `setupDfCovs()`.
#'
#' @param dfCovs The covariate data frame generated by `setupDfCovs()`.
#' @param data The raw data frame used to calculate the reference values. Only the
#'   first record per subject (identified by `idVar`) will be used.
#' @param covariates A character vector of primary covariate base names.
#' @param additionalCovs A character vector of supplementary covariate base names.
#'   Defaults to `NULL`.
#' @param singleRef Logical. If `TRUE` (default), returns a single-row data frame
#'   where all covariates are set to their reference values. If `FALSE`, returns a
#'   data frame with the exact dimensions of `dfCovs`, preserving `missVal` states
#'   while replacing active varying states with reference values.
#' @param contRef A character string indicating how to calculate the reference
#'   value for continuous covariates. Must be either `"median"` or `"mean"`.
#'   Defaults to `"median"`.
#' @param minLevels The maximum number of unique values a covariate can have to be
#'   treated as categorical. Default is 10.
#' @param idVar The name of the subject identifier column. Defaults to `"ID"`.
#' @param missVal The numeric value indicating missing data in `dfCovs`. Defaults to -99.
#' @param nsig The number of significant digits for rounding continuous covariates.
#'   Defaults to 3.
#' @param refLevels An optional named list giving the reference level for
#'   individual multi-level categorical covariates, e.g. `list(GENO = 2)`. Must
#'   match the `refLevels` passed to `setupDfCovs()` so the reference column
#'   names line up. Covariates not named here use their lowest level as the
#'   reference.
#' @param sep The separator between the covariate name and the level in the
#'   one-hot column names. Defaults to `"_"`; must match `setupDfCovs()`.
#'
#' @return A data frame formatted to be passed as the `dfRefRow` argument.
#' @export
#'
#' @examples
#' dfData <- read.csv(
#'   system.file("extdata", "SimVal/DAT-1-MI-PMX-2.csv", package = "PMXForest")
#' )
#' covs   <- c("WT", "AGE", "SEX", "GENO")
#' dfCovs <- setupDfCovs(dfData, covariates = covs, idVar = "ID")
#'
#' # Single-row reference: every covariate at its mode / median
#' setupDfRefRow(dfCovs, data = dfData, covariates = covs, idVar = "ID")
#'
#' # Matrix reference: same shape as dfCovs, active cells set to the reference,
#' # inactive cells keep missVal
#' setupDfRefRow(dfCovs, data = dfData, covariates = covs, singleRef = FALSE,
#'               idVar = "ID")
setupDfRefRow <- function(dfCovs, data, covariates, additionalCovs = NULL,
                          singleRef = TRUE, contRef = c("median", "mean"),
                          minLevels = 10, idVar = "ID", missVal = -99, nsig = 3,
                          refLevels = NULL, sep = "_") {

  contRef <- match.arg(contRef)
  all_covs <- unique(c(covariates, additionalCovs))

  # 1. Deduplicate baseline data to maintain consistency
  dedup_data <- data %>% dplyr::distinct(!!rlang::sym(idVar), .keep_all = TRUE)

  get_mode <- function(x) {
    ux <- unique(x)
    ux[which.max(tabulate(match(x, ux)))]
  }

  # 2. Compute the exact reference values for every column
  ref_map <- list()
  for (cov in all_covs) {
    v <- dedup_data[[cov]][dedup_data[[cov]] != missVal & !is.na(dedup_data[[cov]])]
    if (length(v) == 0) stop(paste("Covariate", cov, "contains only missing values."))

    n_levs <- length(unique(v))
    if (n_levs <= minLevels) {
      mode_val <- get_mode(v)
      if (n_levs == 2) {
        ref_map[[cov]] <- mode_val
      } else {
        levs   <- sort(unique(v))
        refLev <- if (!is.null(refLevels[[cov]])) refLevels[[cov]] else levs[1]
        for (lev in setdiff(levs, refLev)) {
          col_name <- paste0(cov, sep, lev)
          ref_map[[col_name]] <- ifelse(mode_val == lev, 1, 0)
        }
      }
    } else {
      ref_val <- if (contRef == "median") median(v) else mean(v)
      ref_map[[cov]] <- signif(ref_val, nsig)
    }
  }

  # 3. Construct Output Geometry
  if (singleRef) {
    df_out <- dfCovs[1, , drop = FALSE]
    for (col in names(df_out)) {
      if (col %in% names(ref_map)) {
        df_out[[col]] <- ref_map[[col]]
      } else if (col %in% c("COVARIATEGROUPS", "COVNAME")) {
        df_out[[col]] <- "Reference"
      } else {
        # Fallback for unexpected trailing structural columns
        df_out[[col]] <- NA
      }
    }
    row.names(df_out) <- NULL
    return(df_out)

  } else {
    df_out <- dfCovs
    for (col in names(df_out)) {
      if (col %in% names(ref_map)) {
        # If the cell is missVal, keep it missVal.
        # Otherwise (active state or existing reference), overwrite with the computed reference.
        df_out[[col]] <- ifelse(df_out[[col]] == missVal, missVal, ref_map[[col]])
      }
    }
    return(df_out)
  }
}
