#' Setup Reference Row(s) for Forest Plots
#'
#' @description Generates the reference data frame (`dfRefRow`) required by
#'   `getForestDF` functions. It computes the baseline reference values and maps
#'   them onto the structure of the provided `dfCovs`.
#'
#' @details
#'   **Choosing the reference.** `contRef` and `catRef` both accept either a
#'   single setting applied to every covariate, or a named list with an entry per
#'   covariate plus an optional `default` component:
#'   \itemize{
#'     \item continuous - a number, `"mean"`, `"median"` (default) or `"model"`;
#'     \item categorical - a level, `"mode"` (default), `"lowest"` or `"model"`.
#'   }
#'   For example `contRef = list(WT = 75, AGE = "mean", default = "median")`.
#'
#'   **`"model"` and why it usually matters.** A parameter function derived from
#'   the control stream falls back to the model's own reference whenever a
#'   covariate is inactive - the normalisation constant in `(WT/75)`, or the
#'   branch PsN's scm marks `; Most common`. If the reference row instead uses a
#'   statistic of the data, the two disagree and every row where that covariate
#'   is inactive is displaced from 1. Setting `contRef = "model"` and
#'   `catRef = "model"`, with `model` pointing at the control stream (or at the
#'   list returned by [createParamFunction()]), removes that mismatch by
#'   construction. Statistics are otherwise computed on **deduplicated baseline
#'   data**, one record per `idVar`, matching [setupDfCovs()].
#'
#'   **Categorical covariates.** An explicit `catRef` level is both the reference
#'   subject's level and, for a multi-level covariate, the level dropped when
#'   one-hot encoding - so pass the same `catRef` here as to [setupDfCovs()]. Left
#'   unset, the reference subject takes the most common level while the encoding
#'   drops the lowest, which is the behaviour of earlier versions.
#'
#' @param dfCovs The covariate data frame generated by [setupDfCovs()].
#' @param data The raw data frame used to calculate the reference values. Only
#'   the first record per subject (identified by `idVar`) is used.
#' @param covariates A character vector of primary covariate base names - the
#'   covariates a reference should be **computed from the data** for. Base names,
#'   not encoded column names: `GENO` rather than `GENO_2`, `GENO_3`, `GENO_4`.
#'   It need not cover every column of `dfCovs`. A `dfCovs` column with no
#'   reference resolved for it is set to `missVal`, which a parameter function
#'   reads as "not active here" and answers with its own reference - so leaving a
#'   covariate out means *use the model's reference for this one*. A message
#'   names any columns this applies to.
#' @param conditionalCovs A character vector of supplementary covariate base
#'   names. Defaults to `NULL`.
#' @param singleRef Logical. If `TRUE` (default), returns a single-row data frame
#'   with every covariate at its reference value. If `FALSE`, returns a data
#'   frame with the dimensions of `dfCovs`, preserving `missVal` states while
#'   replacing active states with reference values.
#' @param contRef Reference setting for continuous covariates: a number,
#'   `"mean"`, `"median"` (default) or `"model"`, or a named list of those with an
#'   optional `default` component.
#' @param catRef Reference setting for categorical covariates: a level, `"mode"`
#'   (default), `"lowest"` or `"model"`, or a named list of those with an optional
#'   `default` component. Replaces `refLevels`. When `dfCovs` came from
#'   [setupDfCovs()] this defaults to the `catRef` that call used, so it does not
#'   normally need repeating; supplying it here overrides that.
#' @param model The NONMEM control stream, required when any reference is set to
#'   `"model"`. Either a path to the `.mod` file or the list returned by
#'   [createParamFunction()].
#' @param refLevels Deprecated. Use `catRef`.
#' @param minLevels The maximum number of unique values a covariate can have to
#'   be treated as categorical. Default is 10.
#' @param idVar The name of the subject identifier column. Defaults to `"ID"`.
#' @param missVal The numeric value indicating missing data in `dfCovs`. Defaults
#'   to -99.
#' @param nsig The number of significant digits used when rounding a computed
#'   mean or median. An explicitly supplied value is never rounded. Defaults to 3.
#' @param sep The separator between the covariate name and the level in the
#'   one-hot column names. When `dfCovs` came from [setupDfCovs()] this defaults
#'   to the separator that call used, so it does not normally need repeating;
#'   otherwise `"_"`. Supplying it here overrides the recorded value.
#'
#' @return A data frame formatted to be passed as the `dfRefRow` argument.
#' @export
#'
#' @seealso [setupDfCovs()], [createParamFunction()]
#'   `vignette("Part3-deep-dive-forest-plot-inputs", package = "PMXForest")` for how this fits the whole
#'   workflow.
#'
#' @examples
#' dfData <- read.csv(
#'   system.file("extdata", "SimVal/DAT-1-MI-PMX-2.csv", package = "PMXForest")
#' )
#' covs <- c("WT", "AGE", "SEX", "GENO")
#' dfCovs <- setupDfCovs(dfData, covariates = covs, idVar = "ID")
#'
#' # Single-row reference: every covariate at its mode / median
#' setupDfRefRow(dfCovs, data = dfData, covariates = covs, idVar = "ID")
#'
#' # Matrix reference: same shape as dfCovs, active cells set to the reference,
#' # inactive cells keep missVal
#' setupDfRefRow(dfCovs,
#'   data = dfData, covariates = covs, singleRef = FALSE,
#'   idVar = "ID"
#' )
#'
#' # Pin WT at the model's normalisation weight and take AGE from the mean
#' setupDfRefRow(dfCovs,
#'   data = dfData, covariates = covs, idVar = "ID",
#'   contRef = list(WT = 75, default = "mean")
#' )
#'
#' # Take every reference from the control stream, so the reference row agrees
#' # with a parameter function generated from the same model
#' modFile <- system.file("extdata", "SimVal/run7.mod", package = "PMXForest")
#' covs2 <- c("WT", "SEX", "FOOD", "FORM")
#' dfCovs2 <- setupDfCovs(dfData, covariates = covs2, idVar = "ID")
#' setupDfRefRow(dfCovs2,
#'   data = dfData, covariates = covs2, idVar = "ID",
#'   contRef = "model", catRef = "model", model = modFile
#' )
setupDfRefRow <- function(dfCovs, data, covariates, conditionalCovs = NULL,
                          singleRef = TRUE, contRef = "median", catRef = NULL,
                          model = NULL, refLevels = NULL, minLevels = 10,
                          idVar = "ID", missVal = -99, nsig = 3, sep = "_") {
  ## Close the loop with setupDfCovs(): it recorded the catRef and sep that
  ## decided the one-hot column names, so they do not have to be repeated here
  ## and kept in step by hand. An argument given explicitly always wins; the
  ## attribute is only consulted when one was not. It is absent when dfCovs was
  ## built some other way, or subset after being built, in which case this is a
  ## no-op and the arguments behave exactly as before.
  setup <- attr(dfCovs, "pmxCovSetup")
  if (!is.null(setup)) {
    if (is.null(catRef) && is.null(refLevels)) catRef <- setup$catRef
    if (missing(sep)) sep <- setup$sep
  }

  catRef <- refLevelsToCatRef(refLevels, catRef, "setupDfRefRow")
  all_covs <- unique(c(covariates, conditionalCovs))

  # 1. Resolve one reference value per covariate.
  refs <- refResolve(data, all_covs,
    contRef = contRef, catRef = catRef,
    model = model, minLevels = minLevels, idVar = idVar,
    missVal = missVal, nsig = nsig, catFallback = "mode"
  )

  unsure <- names(refs)[!vapply(refs, `[[`, logical(1), "confident")]
  if (length(unsure) > 0) {
    warning("The reference value for ", paste(unsure, collapse = ", "),
      " was inferred from the model rather than stated by it. Check it, ",
      "and set it explicitly through contRef / catRef if it is wrong.",
      call. = FALSE
    )
  }

  # 2. Map the references onto the columns of dfCovs. A multi-level categorical
  #    appears as one-hot dummies, so its reference has to be expanded.
  dedup <- data %>% dplyr::distinct(!!rlang::sym(idVar), .keep_all = TRUE)
  ref_map <- list()

  for (cov in all_covs) {
    v <- refValues(dedup, cov, missVal)
    type <- refCovType(v, minLevels)
    value <- refs[[cov]]$value

    if (type == "multi") {
      levs <- sort(unique(v))
      # The level dropped when encoding: an explicit catRef, else the lowest.
      encLev <- refEncodingLevel(catRef, cov, levs, model, missVal)
      if (is.null(encLev)) encLev <- refMode(v)
      for (lev in setdiff(levs, encLev)) {
        ref_map[[paste0(cov, sep, lev)]] <- as.numeric(value == lev)
      }
    } else {
      ref_map[[cov]] <- value
    }
  }

  # 3. Construct the output geometry.
  if (singleRef) {
    df_out <- dfCovs[1, , drop = FALSE]

    ## A covariate column of dfCovs that no reference was resolved for would be
    ## filled with NA below, and every parameter computed on this row would then
    ## be NA - silently, since the parameter function is handed a valid row.
    ## Usually this means a covariate was passed to setupDfCovs() but not here.
    unmapped <- setdiff(
      names(df_out),
      c(names(ref_map), "COVARIATEGROUPS", "COVNAME")
    )
    if (length(unmapped) > 0) {
      message(
        "No reference value was resolved for the dfCovs column(s) ",
        paste(unmapped, collapse = ", "),
        "; they are set to ", missVal, " in the reference row, so the ",
        "parameter function will use whatever reference it falls back to for ",
        "them - for a generated function, the one read out of $PK. Add them to ",
        "`covariates` / `conditionalCovs` to take the reference from the data ",
        "instead."
      )
    }

    for (col in names(df_out)) {
      if (col %in% names(ref_map)) {
        df_out[[col]] <- ref_map[[col]]
      } else if (col %in% c("COVARIATEGROUPS", "COVNAME")) {
        df_out[[col]] <- "Reference"
      } else {
        ## A dfCovs column with no resolved reference. missVal, not NA: it means
        ## "this covariate is not active on this row", which every parameter
        ## function already handles by falling back to its own reference. NA
        ## means nothing to them - the generated preamble tests
        ## `df[[cov]] != missVal`, and `if (NA)` is an error, not a missing
        ## result. This also matches singleRef = FALSE, which has always left
        ## such cells at missVal.
        df_out[[col]] <- missVal
      }
    }
    row.names(df_out) <- NULL
    ## pmxCovSetup describes how dfCovs was built and says nothing about a
    ## reference row, so it does not travel with one.
    attr(df_out, "pmxCovSetup") <- NULL
    return(df_out)
  } else {
    df_out <- dfCovs
    for (col in names(df_out)) {
      if (col %in% names(ref_map)) {
        # If the cell is missVal, keep it missVal. Otherwise (active state or
        # existing reference), overwrite with the computed reference.
        df_out[[col]] <- ifelse(df_out[[col]] == missVal, missVal, ref_map[[col]])
      }
    }
    ## pmxCovSetup describes how dfCovs was built and says nothing about a
    ## reference row, so it does not travel with one.
    attr(df_out, "pmxCovSetup") <- NULL
    return(df_out)
  }
}
