#' Check a Generated Parameter Function Against a NONMEM Table
#'
#' @description Evaluates the function generated by [createParamFunction()] over
#'   the rows of a NONMEM `$TABLE` file and compares the result with the values
#'   NONMEM itself wrote. This turns "do I trust the translation?" into a
#'   pass/fail check per parameter.
#'
#' @details
#'   **Why the table rather than the input data.** `$TABLE` output is written
#'   after `IGNORE` and `ACCEPT` have been applied, so a table row always
#'   corresponds to a record the model actually used. Taking the covariates from
#'   the same file as the parameters therefore removes any need to reproduce the
#'   `$DATA` filtering, and removes the risk of comparing misaligned rows. Add
#'   the covariates and the parameters to your `$TABLE` and no filtering logic is
#'   needed here at all.
#'
#'   **Typical versus individual values.** A generated function returns typical
#'   values, but NONMEM tables individual ones. Where a parameter is written
#'   `P = <expr> * EXP(ETA(n))` in `$PK`, [createParamFunction()] records the ETA
#'   index in its `etaMap`, and this function divides the tabled value by
#'   `exp(ETA(n))` to recover the typical value - so the ETA column must also be
#'   in the table. A column named `TVP` is used directly when present and needs
#'   no ETA. Parameters that can be reconciled in neither way are reported with
#'   `PASS = NA` and a warning rather than being silently compared.
#'
#'   **Tolerance.** NONMEM's default table format carries about five significant
#'   digits, so agreement closer than roughly `1e-5` relative cannot be observed.
#'   The default `tol` of `1e-4` sits just above that floor.
#'
#'   Anything missing from the table produces a **loud warning** and a row with
#'   `PASS = NA`; the function still returns a report for the parameters it could
#'   check.
#'
#' @param x The list returned by [createParamFunction()].
#' @param tabFile Path to a NONMEM table file (an `sdtab` / `patab` / `xptab`).
#'   The first line is the `TABLE NO.` banner and the second the column header.
#' @param thetas A numeric vector of THETA values, normally the final estimates,
#'   e.g. `as.numeric(getExt(extFile)[getExt(extFile)$ITERATION == -1000000000,
#'   2:15])`.
#' @param fun The function to check. Defaults to the one in `x$code`; supply it
#'   explicitly if you have edited the generated source.
#' @param parameters A character vector of parameters to check. Defaults to all
#'   of `x$functionListName`.
#' @param tol Relative tolerance for a pass. Defaults to `1e-4`.
#' @param idVar Column identifying subjects, used only to report how many
#'   subjects were covered. Defaults to `"ID"`.
#' @param quiet Logical. If `FALSE` (default), reports the outcome per parameter.
#'
#' @return A data frame with one row per parameter: `PARAMETER`, `TABLECOLUMN`,
#'   `N`, `MAXABSDIFF`, `MAXRELDIFF` and `PASS`. The per-row values are attached
#'   as the `"detail"` attribute.
#'
#' @seealso [createParamFunction()]
#'
#' @export
#'
#' @examples
#' modFile <- system.file("extdata", "SimVal/run7.mod", package = "PMXForest")
#' out <- createParamFunction(modFile, parameters = c("CL", "V"), quiet = TRUE)
#'
#' ## `out$etaMap` records that CL and V carry exponential IIV, so a table
#' ## holding CL, V, ETA3, ETA4 and the covariates can be reconciled directly:
#' out$etaMap
#'
#' ## verifyParamFunction(out, tabFile = "xptab7", thetas = thetas)
verifyParamFunction <- function(x, tabFile, thetas, fun = NULL,
                                parameters = NULL, tol = 1e-4, idVar = "ID",
                                quiet = FALSE) {

  if (!is.list(x) || is.null(x$code)) {
    stop("`x` must be the list returned by createParamFunction().", call. = FALSE)
  }
  if (!file.exists(tabFile)) stop("Table file not found: ", tabFile, call. = FALSE)

  if (is.null(fun))        fun <- eval(parse(text = x$code))
  if (is.null(parameters)) parameters <- x$functionListName

  tab <- utils::read.table(tabFile, skip = 1, header = TRUE, check.names = TRUE)

  ## Every covariate the function reads must be in the table. The generated code
  ## silently falls back to the reference value for an absent column, which would
  ## make the comparison meaningless rather than failing, so check explicitly.
  covs        <- names(x$covRef)
  missingCovs <- setdiff(covs, names(tab))
  if (length(missingCovs) > 0) {
    warning("These covariates are not columns of ", basename(tabFile), ": ",
            paste(missingCovs, collapse = ", "),
            ". The generated function will use its reference value for them, so ",
            "the comparison below is NOT a valid check. Add them to $TABLE.",
            call. = FALSE)
  }

  ## One row per distinct covariate combination is enough, and much faster.
  keyCols <- intersect(covs, names(tab))
  rows    <- if (length(keyCols) > 0) tab[!duplicated(tab[, keyCols, drop = FALSE]), ,
                                          drop = FALSE] else tab
  nSubj <- if (idVar %in% names(tab)) length(unique(tab[[idVar]])) else NA_integer_

  ## Evaluate once; the function returns every parameter per call.
  vals <- lapply(seq_len(nrow(rows)), function(i) fun(thetas = thetas,
                                                      df = rows[i, , drop = FALSE]))

  res    <- vector("list", length(parameters))
  detail <- list()

  for (k in seq_along(parameters)) {
    p   <- parameters[k]
    got <- vapply(vals, function(v) as.numeric(v[[p]]), numeric(1))

    tvCol <- paste0("TV", p)
    if (tvCol %in% names(rows)) {
      ref    <- rows[[tvCol]]
      colUse <- tvCol
    } else if (p %in% names(rows)) {
      etaIdx <- x$etaMap[[p]]
      etaCol <- if (!is.null(etaIdx)) paste0("ETA", etaIdx) else NULL
      if (!is.null(etaCol) && etaCol %in% names(rows)) {
        # Tabled value is individual; divide out the exponential IIV.
        ref    <- rows[[p]] / exp(rows[[etaCol]])
        colUse <- paste0(p, " / exp(", etaCol, ")")
      } else {
        warning("Cannot recover typical values of '", p, "' from ",
                basename(tabFile), ": neither a '", tvCol, "' column nor the ",
                if (is.null(etaIdx)) "exponential-IIV pattern in $PK"
                else paste0("'", etaCol, "' column"),
                " is available. Add ", if (is.null(etaIdx)) tvCol else etaCol,
                " to $TABLE.", call. = FALSE)
        res[[k]] <- data.frame(PARAMETER = p, TABLECOLUMN = NA_character_,
                               N = 0L, MAXABSDIFF = NA_real_,
                               MAXRELDIFF = NA_real_, PASS = NA,
                               stringsAsFactors = FALSE)
        next
      }
    } else {
      warning("Parameter '", p, "' is not a column of ", basename(tabFile),
              ". Add it to $TABLE to verify it.", call. = FALSE)
      res[[k]] <- data.frame(PARAMETER = p, TABLECOLUMN = NA_character_,
                             N = 0L, MAXABSDIFF = NA_real_,
                             MAXRELDIFF = NA_real_, PASS = NA,
                             stringsAsFactors = FALSE)
      next
    }

    absd <- abs(got - ref)
    reld <- absd / pmax(abs(ref), .Machine$double.eps)
    ok   <- if (length(missingCovs) > 0) NA else max(reld) <= tol

    res[[k]] <- data.frame(PARAMETER = p, TABLECOLUMN = colUse,
                           N = length(ref), MAXABSDIFF = max(absd),
                           MAXRELDIFF = max(reld), PASS = ok,
                           stringsAsFactors = FALSE)
    detail[[p]] <- data.frame(generated = got, table = ref, absdiff = absd,
                              reldiff = reld)
  }

  out <- do.call(rbind, res)
  attr(out, "detail") <- detail

  if (!quiet) {
    message("Checked ", nrow(rows), " distinct covariate combination(s)",
            if (!is.na(nSubj)) paste0(" from ", nSubj, " subject(s)") else "",
            " in ", basename(tabFile), ".")
    for (i in seq_len(nrow(out))) {
      message("  ", out$PARAMETER[i], ": ",
              if (is.na(out$PASS[i])) "not verified"
              else if (out$PASS[i]) paste0("pass (max rel diff ",
                                           signif(out$MAXRELDIFF[i], 3), ")")
              else paste0("FAIL (max rel diff ", signif(out$MAXRELDIFF[i], 3),
                          ", tolerance ", tol, ")"))
    }
  }

  out
}
